/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Stream
         * @description Answer a question, streaming pipeline progress as newline-delimited JSON.
         *
         *     Emits ``step_start``/``step_end`` events as pipeline steps begin and finish,
         *     followed by a terminal ``done`` event carrying the ``QueryResponse`` (or an
         *     ``error`` event). The client shows every step that has started but not ended.
         */
        post: operations["query_stream_api_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description List a client's conversations, newest first, with cursor pagination.
         */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a specific conversation by ID.
         */
        get: operations["get_conversation_api_conversations__conversation_uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Get list of available models.
         */
        get: operations["get_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Example Question
         * @description Get a random example question for the specified language.
         */
        get: operations["get_example_question_api_example_question_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/citations/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Citations Batch
         * @description Get multiple citations in a single request.
         *
         *     Supports fetching different chunks from different files.
         *     Returns partial results with successes and errors separated.
         */
        post: operations["get_citations_batch_api_citations_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description Get list of all categories for a language.
         */
        get: operations["get_categories_api_library_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/files/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Files
         * @description Get list of files in a category for a language.
         */
        get: operations["get_files_api_library_files__category__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/file/{category}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Get full text content of a file by category and id.
         */
        get: operations["get_file_api_library_file__category___id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/quest-hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quest Hierarchy
         * @description Get the browsable quest hierarchy (type -> series -> chapter -> quest).
         */
        get: operations["get_quest_hierarchy_api_library_quest_hierarchy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/quest-series/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quest Series
         * @description Get the series (or lone chapter) enclosing a quest, for its detail-page TOC.
         */
        get: operations["get_quest_series_api_library_quest_series__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve Library
         * @description Retrieve library documents using BM25 or hybrid semantic search.
         */
        post: operations["retrieve_library_api_library_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/short-urls/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Short Url
         * @description Resolve a short URL slug to its target path.
         */
        get: operations["resolve_short_url_api_short_urls__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Get version information.
         */
        get: operations["get_version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CitationBatchRequest
         * @description Request model for batch citation endpoint.
         */
        CitationBatchRequest: {
            /** Language */
            language: string;
            /** Citations */
            citations: [
                string,
                number
            ][];
        };
        /**
         * CitationBatchResponse
         * @description Response model for batch citation endpoint.
         */
        CitationBatchResponse: {
            /** Successes */
            successes: components["schemas"]["CitationResponse"][];
            /** Errors */
            errors: components["schemas"]["CitationError"][];
        };
        /**
         * CitationError
         * @description Error details for a failed citation fetch.
         */
        CitationError: {
            /** File Id */
            file_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Error */
            error: string;
        };
        /**
         * CitationResponse
         * @description Response model for citation content endpoint.
         */
        CitationResponse: {
            /** File Id */
            file_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Total Chunks */
            total_chunks: number;
            file_info: components["schemas"]["LibraryFileInfo"];
        };
        /**
         * ConversationListResponse
         * @description Response model for listing a client's conversations, newest first.
         */
        ConversationListResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationSummary"][];
        };
        /**
         * ConversationResponse
         * @description Response model for conversation retrieval.
         */
        ConversationResponse: {
            /** Uuid */
            uuid: string;
            /** Language */
            language: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Model */
            model: string;
            /** K */
            k: number;
            /** Created At */
            created_at: number;
            /** Generation Time Seconds */
            generation_time_seconds: number;
            /** Final Generation Input Text Length */
            final_generation_input_text_length: number;
            /** Retrieval Unique Chunk Count */
            retrieval_unique_chunk_count: number;
            /** Retrieval Unique File Count */
            retrieval_unique_file_count: number;
            /** Short Slug */
            short_slug: string;
        };
        /**
         * ConversationSummary
         * @description Lightweight conversation metadata for the history list.
         */
        ConversationSummary: {
            /** Id */
            id: number;
            /** Uuid */
            uuid: string;
            /** Question */
            question: string;
            /** Language */
            language: string;
            /** Model */
            model: string;
            /** Created At */
            created_at: number;
        };
        /**
         * ExampleQuestionResponse
         * @description Response model for example question endpoint.
         */
        ExampleQuestionResponse: {
            /** Question */
            question: string;
            /** Language */
            language: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LibraryCategoriesResponse
         * @description Response model for library categories endpoint.
         */
        LibraryCategoriesResponse: {
            /** Categories */
            categories: string[];
        };
        /**
         * LibraryFileInfo
         * @description File information with parsed components.
         */
        LibraryFileInfo: {
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Id */
            id: number;
            /** Relative Path */
            relative_path: string;
        };
        /**
         * LibraryFileResponse
         * @description Response model for library file content endpoint.
         */
        LibraryFileResponse: {
            file_info: components["schemas"]["LibraryFileInfo"];
            /** Content */
            content: string;
        };
        /**
         * LibraryFilesResponse
         * @description Response model for library files endpoint.
         */
        LibraryFilesResponse: {
            /** Files */
            files: components["schemas"]["LibraryFileInfo"][];
        };
        /**
         * LibraryRetrieveRequest
         * @description Request model for library retrieval endpoint.
         */
        LibraryRetrieveRequest: {
            /** Language */
            language: string;
            /** Query */
            query: string;
            /** K */
            k: number;
            /**
             * Semantic
             * @default false
             */
            semantic: boolean;
            /**
             * Chunk Context
             * @default 0
             */
            chunk_context: number;
        };
        /**
         * LibraryRetrieveResponse
         * @description Response model for library retrieval endpoint.
         */
        LibraryRetrieveResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["LibraryRetrieveResult"][];
        };
        /**
         * LibraryRetrieveResult
         * @description Single retrieved library document with snippet.
         */
        LibraryRetrieveResult: {
            file_info: components["schemas"]["LibraryFileInfo"];
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
        };
        /**
         * ModelsResponse
         * @description Response model for available models endpoint.
         */
        ModelsResponse: {
            /** Models */
            models: string[];
            /** Default */
            default: string;
        };
        /**
         * QueryRequest
         * @description Request model for query endpoint.
         */
        QueryRequest: {
            /** Language */
            language: string;
            /** Question */
            question: string;
            /** Model */
            model: string;
            /** K */
            k: number;
            /** Chunk Context */
            chunk_context: number;
            /** Client Id */
            client_id?: string | null;
        };
        /**
         * QueryResponse
         * @description Response model for query endpoint.
         */
        QueryResponse: {
            /** Language */
            language: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Conversation Uuid */
            conversation_uuid: string;
            /** Short Slug */
            short_slug: string;
            /** Final Generation Input Text Length */
            final_generation_input_text_length: number;
            /** Retrieval Unique Chunk Count */
            retrieval_unique_chunk_count: number;
            /** Retrieval Unique File Count */
            retrieval_unique_file_count: number;
        };
        /**
         * QueryStreamDone
         * @description Terminal event carrying the completed answer.
         */
        QueryStreamDone: {
            /**
             * Type
             * @default done
             * @constant
             */
            type: "done";
            result: components["schemas"]["QueryResponse"];
        };
        /**
         * QueryStreamError
         * @description Terminal event signalling the query failed.
         */
        QueryStreamError: {
            /**
             * Type
             * @default error
             * @constant
             */
            type: "error";
            /** Error */
            error: string;
        };
        /**
         * QueryStreamStepEnd
         * @description A previously started pipeline step has ended.
         */
        QueryStreamStepEnd: {
            /**
             * Type
             * @default step_end
             * @constant
             */
            type: "step_end";
            /** Id */
            id: string;
        };
        /**
         * QueryStreamStepStart
         * @description A pipeline step has started (shown until its matching step_end).
         */
        QueryStreamStepStart: {
            /**
             * Type
             * @default step_start
             * @constant
             */
            type: "step_start";
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Detail */
            detail: string | null;
        };
        /**
         * QuestHierarchyChapter
         * @description One chapter (act) grouping a set of quests.
         */
        QuestHierarchyChapter: {
            /** Chapter Id */
            chapter_id: number;
            /** Chapter Title */
            chapter_title: string;
            /** Quests */
            quests: components["schemas"]["QuestHierarchyQuest"][];
        };
        /**
         * QuestHierarchyQuest
         * @description A single quest leaf in the quest hierarchy.
         */
        QuestHierarchyQuest: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /**
         * QuestHierarchyResponse
         * @description Response model for the quest hierarchy endpoint.
         */
        QuestHierarchyResponse: {
            /** Types */
            types: components["schemas"]["QuestHierarchyType"][];
        };
        /**
         * QuestHierarchySeries
         * @description A series (questline) grouping chapters that share a chapter group.
         */
        QuestHierarchySeries: {
            /** Series Id */
            series_id: number;
            /** Series Title */
            series_title: string;
            /** Chapters */
            chapters: components["schemas"]["QuestHierarchyChapter"][];
        };
        /**
         * QuestHierarchyType
         * @description A top-level quest type and the quests under it.
         *
         *     ``chapters`` holds chapters with no series; ``standalone_quests`` holds quests
         *     with no chapter.
         */
        QuestHierarchyType: {
            /** Quest Type */
            quest_type: string;
            /** Series */
            series: components["schemas"]["QuestHierarchySeries"][];
            /** Chapters */
            chapters: components["schemas"]["QuestHierarchyChapter"][];
            /** Standalone Quests */
            standalone_quests: components["schemas"]["QuestHierarchyQuest"][];
        };
        /**
         * QuestSeriesResponse
         * @description The series (or lone chapter) enclosing a quest, for the detail-page TOC.
         *
         *     Only returned for a quest present in the hierarchy, so ``quest_type`` (the
         *     enclosing top-level type, used to point the back button at the right type
         *     listing) is always set. ``series`` and ``chapter`` are mutually exclusive and
         *     both null for a standalone quest.
         */
        QuestSeriesResponse: {
            /** Quest Type */
            quest_type: string;
            series?: components["schemas"]["QuestHierarchySeries"] | null;
            chapter?: components["schemas"]["QuestHierarchyChapter"] | null;
        };
        /**
         * ShortURLResponse
         * @description Response model for short URL resolution.
         */
        ShortURLResponse: {
            /** Slug */
            slug: string;
            /** Target Path */
            target_path: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VersionResponse
         * @description Response model for version endpoint.
         */
        VersionResponse: {
            /** Checkpoint Versions */
            checkpoint_versions: {
                [key: string]: string | null;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_stream_api_query_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Newline-delimited JSON (application/x-ndjson) stream of progress events, ending with a `done` or `error` event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryStreamStepStart"] | components["schemas"]["QueryStreamStepEnd"] | components["schemas"]["QueryStreamDone"] | components["schemas"]["QueryStreamError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query: {
                client_id: string;
                limit?: number;
                before_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    get_example_question_api_example_question_get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_citations_batch_api_citations_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitationBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitationBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_api_library_categories_get: {
        parameters: {
            query: {
                /** @description Language code (CHS, ENG) */
                language: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryCategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_files_api_library_files__category__get: {
        parameters: {
            query: {
                /** @description Language code (CHS, ENG) */
                language: string;
            };
            header?: never;
            path: {
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryFilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_library_file__category___id__get: {
        parameters: {
            query: {
                /** @description Language code (CHS, ENG) */
                language: string;
            };
            header?: never;
            path: {
                category: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryFileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quest_hierarchy_api_library_quest_hierarchy_get: {
        parameters: {
            query: {
                /** @description Language code (CHS, ENG) */
                language: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestHierarchyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quest_series_api_library_quest_series__id__get: {
        parameters: {
            query: {
                /** @description Language code (CHS, ENG) */
                language: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_library_api_library_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryRetrieveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryRetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_short_url_api_short_urls__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortURLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
