/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query
         * @description Answer a question using the RAG pipeline.
         */
        post: operations["query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a specific conversation by ID.
         */
        get: operations["get_conversation_api_conversations__conversation_uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Get list of available models.
         */
        get: operations["get_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Example Question
         * @description Get a random example question for the specified language.
         */
        get: operations["get_example_question_api_example_question_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/citations/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Citations Batch
         * @description Get multiple citations in a single request.
         *
         *     Supports fetching different chunks from different files.
         *     Returns partial results with successes and errors separated.
         */
        post: operations["get_citations_batch_api_citations_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description Get list of all categories for a language.
         */
        get: operations["get_categories_api_library_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/files/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Files
         * @description Get list of files in a category for a language.
         */
        get: operations["get_files_api_library_files__category__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/file/{category}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Get full text content of a file by category and id.
         */
        get: operations["get_file_api_library_file__category___id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve Library
         * @description Retrieve library documents using BM25 keyword search only.
         */
        post: operations["retrieve_library_api_library_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CitationBatchRequest
         * @description Request model for batch citation endpoint.
         */
        CitationBatchRequest: {
            /** Language */
            language: string;
            /** Citations */
            citations: [
                string,
                number
            ][];
        };
        /**
         * CitationBatchResponse
         * @description Response model for batch citation endpoint.
         */
        CitationBatchResponse: {
            /** Successes */
            successes: components["schemas"]["CitationResponse"][];
            /** Errors */
            errors: components["schemas"]["CitationError"][];
        };
        /**
         * CitationError
         * @description Error details for a failed citation fetch.
         */
        CitationError: {
            /** File Id */
            file_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Error */
            error: string;
        };
        /**
         * CitationResponse
         * @description Response model for citation content endpoint.
         */
        CitationResponse: {
            /** File Id */
            file_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Total Chunks */
            total_chunks: number;
            file_info: components["schemas"]["LibraryFileInfo"];
        };
        /**
         * ConversationResponse
         * @description Response model for conversation retrieval.
         */
        ConversationResponse: {
            /** Uuid */
            uuid: string;
            /** Language */
            language: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Model */
            model: string;
            /** K */
            k: number;
            /** Created At */
            created_at: number;
            /** Generation Time Seconds */
            generation_time_seconds: number;
        };
        /**
         * ExampleQuestionResponse
         * @description Response model for example question endpoint.
         */
        ExampleQuestionResponse: {
            /** Question */
            question: string;
            /** Language */
            language: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LibraryCategoriesResponse
         * @description Response model for library categories endpoint.
         */
        LibraryCategoriesResponse: {
            /** Categories */
            categories: string[];
        };
        /**
         * LibraryFileInfo
         * @description File information with parsed components.
         */
        LibraryFileInfo: {
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Id */
            id: number;
            /** Relative Path */
            relative_path: string;
        };
        /**
         * LibraryFileResponse
         * @description Response model for library file content endpoint.
         */
        LibraryFileResponse: {
            file_info: components["schemas"]["LibraryFileInfo"];
            /** Content */
            content: string;
        };
        /**
         * LibraryFilesResponse
         * @description Response model for library files endpoint.
         */
        LibraryFilesResponse: {
            /** Files */
            files: components["schemas"]["LibraryFileInfo"][];
        };
        /**
         * LibraryRetrieveRequest
         * @description Request model for BM25-only library retrieval endpoint.
         */
        LibraryRetrieveRequest: {
            /** Language */
            language: string;
            /** Query */
            query: string;
            /** K */
            k: number;
        };
        /**
         * LibraryRetrieveResponse
         * @description Response model for BM25-only library retrieval endpoint.
         */
        LibraryRetrieveResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["LibraryRetrieveResult"][];
        };
        /**
         * LibraryRetrieveResult
         * @description Single retrieved library document with snippet.
         */
        LibraryRetrieveResult: {
            file_info: components["schemas"]["LibraryFileInfo"];
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
        };
        /**
         * ModelsResponse
         * @description Response model for available models endpoint.
         */
        ModelsResponse: {
            /** Models */
            models: string[];
        };
        /**
         * QueryRequest
         * @description Request model for query endpoint.
         */
        QueryRequest: {
            /** Language */
            language: string;
            /** Question */
            question: string;
            /** Model */
            model: string;
            /** K */
            k: number;
            /** Chunk Context */
            chunk_context: number;
        };
        /**
         * QueryResponse
         * @description Response model for query endpoint.
         */
        QueryResponse: {
            /** Language */
            language: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Conversation Uuid */
            conversation_uuid: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    get_example_question_api_example_question_get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_citations_batch_api_citations_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitationBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitationBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_api_library_categories_get: {
        parameters: {
            query: {
                /** @description Language code (CHS, ENG) */
                language: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryCategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_files_api_library_files__category__get: {
        parameters: {
            query: {
                /** @description Language code (CHS, ENG) */
                language: string;
            };
            header?: never;
            path: {
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryFilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_library_file__category___id__get: {
        parameters: {
            query: {
                /** @description Language code (CHS, ENG) */
                language: string;
            };
            header?: never;
            path: {
                category: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryFileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_library_api_library_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryRetrieveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryRetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
